### PR TITLE
I changed a little more than I should have..

### PR DESCRIPTION
**Pull request by gotoAndBliss**
It was a tad lazy of me. My apologies. But you'll find all the info needed to add thumbs into the publications as well here.

### CODE REVIEW

**Comment by gotoAndBliss** [comment]
Sorry, this is the first time I've done a pull request. I probably should have created a new branch.

**Comment by ericmann** [comment]
No worries.  I should be able to work most of it in ... I'll let you know as soon as things are merged (though I probably won't use your changes to the CPT definition ...) :-)

**Comment by gotoAndBliss** [comment]
Ha! :D

Wow cool! Thanks for your interest in my work. Can't thank you enough for
the chance to collaborate.

On Tue, Dec 20, 2011 at 5:39 PM, Eric Mann <
reply@reply.github.com

> wrote:
> 
> No worries.  I should be able to work most of it in ... I'll let you know
> as soon as things are merged (though I probably won't use your changes to
> the CPT definition ...) :-)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/ericmann/WP-Publication-Archive/pull/7#issuecomment-3226604

## 

Daniel Trip Levine
Master Bitmapper Wrapper
HQchannel.com

**Comment by gotoAndBliss** [comment]
Hey were you aware that the openfile.php file has a few errors in it? I'm
working on fixing them now, and I'll commit my findings to your tree.

The issue came up as the only browsers that the download feature work on is
Firefox, Chrome, and IE9. IE 7 - 8, and Safari kick the bucket.

Do you have an example site of a working model of this?

Best!

On Tue, Dec 20, 2011 at 5:54 PM, Daniel Trip Levine <
daniel.levine4@gmail.com> wrote:

> Ha! :D
> 
> Wow cool! Thanks for your interest in my work. Can't thank you enough for
> the chance to collaborate.
> 
> On Tue, Dec 20, 2011 at 5:39 PM, Eric Mann <
> reply@reply.github.com
> 
> > wrote:
> > 
> > No worries.  I should be able to work most of it in ... I'll let you know
> > as soon as things are merged (though I probably won't use your changes to
> > the CPT definition ...) :-)
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/ericmann/WP-Publication-Archive/pull/7#issuecomment-3226604
> 
> ## 
> 
> Daniel Trip Levine
> Master Bitmapper Wrapper
> HQchannel.com

## 

Daniel Trip Levine
Master Bitmapper Wrapper
HQchannel.com

**Comment by ericmann** [comment]
Kick the bucket as in ... what exactly?  I just tested in Chrome, IE7, IE8, IE9, and Safari without issue.  What exactly are you seeing?

I have a test installation running at http://pt3st.eamann.com/about/.  There's a single PDF there that downloads just fine.

**Comment by gotoAndBliss** [comment]
Hmm.. I have my model up at  :
http://hqinternetsolutions.com/Websites/Fabric%20Traditions/?page_id=215

It's causing the file to download a .xhtml file. Of which is just the
redirect error page transposed to a .xhtml file.

If I download it successfully in Firefox, Safari, or IE9, the file is
corrupt, and will not open.

On Thu, Dec 29, 2011 at 4:43 PM, Eric Mann <
reply@reply.github.com

> wrote:
> 
> Kick the bucket as in ... what exactly?  I just tested in Chrome, IE7,
> IE8, IE9, and Safari without issue.  What exactly are you seeing?
> 
> I have a test installation running at http://pt3st.eamann.com/about/.
>  There's a single PDF there that downloads just fine.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/ericmann/WP-Publication-Archive/pull/7#issuecomment-3305488

## 

Daniel Trip Levine
Master Bitmapper Wrapper
HQchannel.com

**Comment by ericmann** [comment]
It's actually caused by the space in your URL (the %20).  It's broken in Chrome as well.  Well, broken as in a file downloads, but the content is of your 404 page, not the streamed document.

**Comment by gotoAndBliss** [comment]
You are a genius. I am donating money to the cause :D

On Thu, Dec 29, 2011 at 6:11 PM, Eric Mann <
reply@reply.github.com

> wrote:
> 
> It's actually caused by the space in your URL (the %20).  It's broken in
> Chrome as well.  Well, broken as in a file downloads, but the content is of
> your 404 page, not the streamed document.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/ericmann/WP-Publication-Archive/pull/7#issuecomment-3306337

## 

Daniel Trip Levine
Master Bitmapper Wrapper
HQchannel.com

**Comment by ericmann** [comment]
So the changes work ... but both the "Add publication" and "Add thumbnail" features are trying to override the `window.send_to_editor` function and collide.  This breaks the simple "Insert into post" functionality of the media uploader ... and I'll need to work on a fix before I can publish an official release.

**Comment by gotoAndBliss** [comment]
Fixed!

```
/* A Trip Function */
public static function doc_thumb_box() {
global $post;

$thumb = get_post_meta( $post->ID, 'upload_image', true );

echo 'Enter a URL or upload an image for the thumb.';
echo '<br />';
echo '<br />';
echo '<label for="upload_image">';
echo '<input id="upload_image" type="text" size="36"
```

name="upload_image" value=" ' . $thumb . '" />';
    echo '<input id="upload_image_button" type="button" value="Upload
Thumb" />';

```
echo "<script type=\"text/javascript\">
jQuery(document).ready(function() {

  jQuery('#upload_image_button').click(function() {

   window.send_to_editor = function(html) {
    imgurl = jQuery('img',html).attr('src');
    jQuery('#upload_image').val(imgurl);
    tb_remove();
   }

   tb_show('', 'media-upload.php?type=image&amp;TB_iframe=true');
   return false;
  });

});
</script>\r\n";

}

public static function doc_uri_box() {
    global $post;

    $uri = get_post_meta( $post->ID, 'wpa_upload_doc', true );
    echo "<style type=\"text/css\">
```

#edit-slug-box {
    display: none;
    }
</style>";
        echo '<p>Please provide the abosulte url of the file (including the
<code>http://</code>):</p>';
        echo '<input type="text" id="wpa_upload_doc" name="wpa_upload_doc"
value="' . $uri . '" size="25" style="width:85%" />';
        echo '<input class="button" id="upload_doc_button" type="button"
value="Upload Publication" alt="Upload Publication" />';
        echo "<script type=\"text/javascript\">

```
jQuery(document).ready(function() {

    jQuery('#upload_doc_button').live('click', function() {

        window.send_to_editor = function(html) {
          var docurl = jQuery(html).attr('href');
          jQuery('#wpa_upload_doc').val(docurl);
          tb_remove();
      }

        tb_show('Upload Publication',
```

'media-upload.php?TB_iframe=1&width=640&height=263');
            return false;
        });

```
});
```

  </script>\r\n";
    }

On Wed, Jan 4, 2012 at 12:01 AM, Eric Mann <
reply@reply.github.com

> wrote:
> 
> So the changes work ... but both the "Add publication" and "Add thumbnail"
> features are trying to override the `window.send_to_editor` function and
> collide.  This breaks the simple "Insert into post" functionality of the
> media uploader ... and I'll need to work on a fix before I can publish an
> official release.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/ericmann/WP-Publication-Archive/pull/7#issuecomment-3350732

## 

Daniel Trip Levine
Master Bitmapper Wrapper
HQchannel.com

**Comment by ericmann** [comment]
Nice. Though I'm using .on() instead of .live() since it's the preferred method according to the jQuery team.  But this should just about do it.  I'll tag it here so you'll have a solid release to work from, but I'll wait to push it to the WP.org repo until later (need to test a couple of backwards compatibility things first).

**Comment by gotoAndBliss** [comment]
Incredible. I apologize for the uncleanliness of pasting it here rather
than committing it to the repo.

I'll do so in the future.

Thanks!

On Wed, Jan 4, 2012 at 10:20 AM, Eric Mann <
reply@reply.github.com

> wrote:
> 
> Nice. Though I'm using .on() instead of .live() since it's the preferred
> method according to the jQuery team.  But this should just about do it.
>  I'll tag it here so you'll have a solid release to work from, but I'll
> wait to push it to the WP.org repo until later (need to test a couple of
> backwards compatibility things first).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/ericmann/WP-Publication-Archive/pull/7#issuecomment-3355775

## 

Daniel Trip Levine
Master Bitmapper Wrapper
HQchannel.com

**Pull request closed without merging**
